spring.application.name=flow
spring.datasource.url=jdbc:postgresql://localhost:5432/workflow
spring.datasource.username=flower
spring.datasource.password=flower
spring.datasource.driver-class-name=org.postgresql.Driver

server.port=9015
